version: "2"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    volumes:
      - ./app:/usr/src/app/app
      - ./config:/usr/src/app/config
      - ./public:/usr/src/app/public
    depends_on:
    - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"
