version: "3.7"
services:
  test:
    build: .
    depends_on:
    - mongo
    command: ["./scripts/wait-for-it.sh", "mongo:27017", "--", "npm", "test"]
  mongo:
    image: mongo
    volumes:
    - ./data:/data/db
