FROM node:12

WORKDIR /usr/src/app

# Environment variables
ENV NODE_ENV='production'

# Install app dependencies
COPY package*.json ./
RUN npm install --production'

# Copy app source code
COPY . .

# Expose port
EXPOSE 3000

# Run as node user for security
USER node

# Run the application
CMD [ "node", "server.js" ]
