version: "3"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    command: ["./scripts/wait-for-it.sh", "mongo:27017", "--", "npm", "test"]
  mongo:
    image: mongo
    volumes:
    - ./data:/data/db
